title: Arnaud Belcour's blog
description: Another blog among the universe

url: "https://arnaudbelcour.github.io"
baseurl: "/blog"
exclude: [".gitignore"]

github_username: ArnaudBelcour
theme: jekyll-theme-slate