title: Arnaud Belcour's blog
description: Arnaud Belcour's blog

url: "https://arnaudbelcour.github.io"
baseurl: "/blog"
exclude: [".gitignore"]

github_username: ArnaudBelcour
theme: jekyll-theme-slate